shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^sweet/list/$', views.sweet_list, name='sweet_list'),
	url(r'^sweet/detail/(?P<sweet_id>\d+)$', views.sweet_detail, name='sweet_detail'),
	url(r'^user/detail/(?P<user_id>\d+)$', views.profile_detail, name='profile_detail'),
	url(r'^sweet/buy/(?P<sweet_id>\d+)$', views.sweet_buy, name='sweet_buy'),
	url(r'^$', views.index, name='main_page'),
	url(r'^manufacturer/list/$', views.manufacturer_list, name='manufacturer_list'),
	url(r'^manufacturer/detail/(?P<manufacturer_id>\d+)$', views.manufacturer_detail, name='manufacturer_detail'),
	url(r'^contact/$', views.contactView, name='contact'),
]

subd_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import shop.urls

urlpatterns = [
	url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(shop.urls)),
]   


from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    

urlpatterns += staticfiles_urlpatterns()

shop/models.py
#coding=utf8
from django.db import models
from django.contrib.auth.models import User, Group, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver


class Country(models.Model):
	name = models.CharField(verbose_name='Страна', max_length=65, unique=True)	
	class Meta:
		ordering = ('name', )
		verbose_name = 'Страна'
		verbose_name_plural = 'Страны'		
	def __str__(self):
		return self.name
			

class Manufacturer(models.Model):
    name = models.CharField(verbose_name='Изготовитель', max_length=100)
    contact_address = models.CharField(verbose_name='Контактный адрес', max_length=250)
    manufacturers_address = models.CharField(
        verbose_name='Адрес производства',
    	max_length = 250
    )
    country = models.ForeignKey(
    	verbose_name='Страна', 
    	to=Country, 
    	null=True, 
    	on_delete=models.CASCADE) 
    def __str__(self):
    	return self.name
    class Meta:
        ordering = ('country', )
        verbose_name = 'Изготовитель'
        verbose_name_plural = 'Изготовители'       
    
    	
    	
    	

class TypeOfSweet(models.Model):
	name = models.CharField(verbose_name='Тип сладости', max_length=50, unique=True)	
	class Meta:
		ordering = ('name', )
		verbose_name = 'Тип сладости'
		verbose_name_plural = 'Типы сладостей'		
	def __str__(self):
		return self.name    
		
		
		
			
    	
class Sweet(models.Model):
    title = models.CharField(verbose_name='Название', max_length=100)
    price_for_one = models.FloatField(verbose_name='Цена за одну штуку', null=True)
    price_weight = models.FloatField(verbose_name='Цена за 100 грамм', blank=True, null=True)
    structure = models.CharField(verbose_name='Состав', max_length=201)
    description = models.CharField(verbose_name='Описание', max_length=200)
    manufacturer = models.ForeignKey(
    	verbose_name='Изготовитель', 
    	to=Manufacturer,
    	null=True, 
    	on_delete=models.CASCADE
    )
    typeOfSweet = models.ForeignKey(
    	verbose_name='Тип сладости',
    	to=TypeOfSweet, 
    	on_delete=models.CASCADE,
    	null=True
    )
      
    class Meta:
        ordering = ('title', 'manufacturer', )
        verbose_name = 'Сладость'
        verbose_name_plural = 'Сладости' 
        permissions = (
        	('buy_sweet' , 'Купить сладость'),
        )       
    def __str__(self):
    	return self.title
    	
    	
class Profile(models.Model):
	user = models.OneToOneField(
		User, 
		unique=True,
		on_delete=models.CASCADE
	)
	bio = models.TextField(max_length=500, blank=True, null=True)
	vk_page = models.CharField(verbose_name='Страница Вконтакте',max_length=30,blank=True, null=True)
	balance = models.FloatField(verbose_name='Баланс', default=100.0)
	timezone = models.CharField(verbose_name='Часовой пояс',max_length=50, default='Europe/Moscow')
	
	def __str__(self):
		return self.user.username
	
		

@receiver(post_save, sender=User)	
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
      

@receiver(post_save, sender=User)	
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    
@receiver(post_save, sender=User, dispatch_uid='myproject.myapp.models.user_post_save_handler')
def user_post_save(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='Пользователи'))
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

shop/forms.py
from django import forms
from shop.models import Profile, Sweet
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('vk_page', 'timezone')

class SweetBuyForm(forms.Form):
	price1 = forms.IntegerField(label='Сколько вы хотите купить штук?', min_value = 0, initial=1)
	price2 = forms.IntegerField(label='Сколько вы хотите купить на вес? (В граммах, минимум 100)', min_value=100, required=False)
	
class ContactForm(forms.Form):
	subject = forms.CharField(max_length = 100)
	sender = forms.EmailField()
	message = forms.CharField(widget = forms.Textarea(attrs = {'class': 'form-control'}))
	copy = forms.BooleanField(required = False)
		
	
        

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from shop.models import Sweet, Manufacturer
from django.template import Context, loader
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User, Group
from shop.forms import UserForm, ProfileForm, SweetBuyForm, ContactForm 
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError


def sweet_list(request):
	sweets_list = Sweet.objects.select_related('typeOfSweet')
	paginator = Paginator(sweets_list, 15)	
	page = request.GET.get('page')
	try:
		sweets = paginator.page(page)
	except PageNotAnInteger:
		sweets = paginator.page(1)
	except EmptyPage:
		sweets = paginator.page(paginator.num_pages)
	
	return render(request, 'sweet/sweet_list.html', {'sweets' : sweets})
		
	
def sweet_detail(request, sweet_id):
	try:
		sweet = Sweet.objects.select_related('manufacturer', 'typeOfSweet').get(id=sweet_id)
	except Sweet.DoesNotExist:
		raise Http404
	return render (
		request, 'sweet/sweet_detail.html',
		{'sweet' : sweet}
	)

def sweet_buy(request, sweet_id):
	try:
		sweet = Sweet.objects.select_related('typeOfSweet').get(id=sweet_id)
	except Sweet.DoesNotExist:
		raise Http404	
	if request.method == 'POST':
		form = SweetBuyForm(request.POST)
		if form.is_valid():
			price1 = form.cleaned_data['price1']
			if form.cleaned_data['price2']==None:
				price2 = 0
			else:
				price2 = form.cleaned_data['price2']
			try:			
				price = price1*sweet.price_for_one + (price2/100)*sweet.price_weight
			except TypeError:
				price = price1*sweet.price_for_one
			if request.user.profile.balance >= price:
				request.user.profile.balance -= price
				request.user.profile.save()
				return render(
				request, 'sweet/sweet_thanks.html',			
				)
			else :
				return render(
					request, 'sweet/sweet_nomoney.html'
				)
					
	else:
		form = SweetBuyForm()
	return render (
		request, 'sweet/sweet_buy.html', {
			'form' : form,
			'sweet' : sweet
		}
	)



@login_required
@transaction.atomic	
def profile_detail(request, user_id):
	try:
		user = User.objects.select_related('profile').get(id=user_id)
	except User.DoesNotExist:
		raise Http404
	if request.method == 'POST':
		user_form = UserForm(request.POST, instance=request.user)
		profile_form = ProfileForm(request.POST, instance=request.user.profile)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, ('Your profile was successfully updated!'))
		else:
			messages.error(request, ('Please correct the error below.'))
	else:
		user_form = UserForm(instance=request.user)
		profile_form = ProfileForm(instance=request.user.profile)
	return render (
		request, 'profile/profile_detail.html', {
			'user' : user,
			'user_form': user_form,
	       	'profile_form': profile_form
		}	
	)



def index(request):
	return render(request, 'index.html')
	
	
	
def manufacturer_list(request):
	manufacturer_list = Manufacturer.objects.select_related('country')
	paginator = Paginator(manufacturer_list, 15)	
	page = request.GET.get('page')
	try:
		mans = paginator.page(page)
	except PageNotAnInteger:
		mans = paginator.page(1)
	except EmptyPage:
		mans = paginator.page(paginator.num_pages)	
	return render(request, 'manufacturer/manufacturer_list.html', {'manufacturers' : mans})
		
	
def manufacturer_detail(request, manufacturer_id):
	try:
		manufacturer = Manufacturer.objects.select_related('country').get(id=manufacturer_id)
	except Manufacturer.DoesNotExist:
		raise Http404
	return render (
		request, 'manufacturer/manufacturer_detail.html',
		{'manufacturer' : manufacturer}
	)

def contactView(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			subject = form.cleaned_data['subject']
			sender = form.cleaned_data['sender']
			message = form.cleaned_data['message']
			copy = form.cleaned_data['copy']
			recipients = ['mzkmobile@yandex.ru']			
			if copy:
				recipients.append(sender)
			try:
				send_mail(subject, message, 'ProjectWorkMail@yandex.ru', recipients)
			except BadHeaderError: 
				return HttpResponse('Invalid header found')
			return render(request, 'contact/contact_thanks.html')
	else:
		form = ContactForm()
	return render(request, 'contact/contact.html', {'form': form})	
	
	


	

		
		
	
	
		

shop/templates/sweet/sweet_buy.html
{% extends 'shop_base.html' %}
{% block title %}
	Купить {{sweet.title}}
{% endblock %}
{% block content %}
	{% if user.is_authenticated %}	
		<form method="post">
			{% csrf_token %}
			{{form.non_field_errors }}
			<div>
				<label for="id_price1">Количество в штуках:</label>
				{{ form.price1.errors }}
				{{ form.price1 }}
			</div>
			<div>
				<label for="id_price2">Количество в граммах (минимум 100):</label>
				{{ form.price2.errors }}
				{{ form.price2 }}
			</div>
			<input type="submit" value="Оплатить"/>		
		</form>
	{% else %}
		<h1>Войдите или зарегистрируйтесь, чтобы совершать покупки</h1>
	{% endif %}
{% endblock %}

shop/templates/sweet/sweet_detail.html
{% extends 'shop_base.html' %}
{% block title %}
	Информация о {{sweet.title}}
{% endblock %}
{% block content %}
	<h1>{{sweet.title}}</h1>
	<table border="3" cellpadding="10" bordercolor= "blue">
		<tr>
   			<td>Тип</td>
   			<td>Изготовитель</td>
  			<td>Цена за одну штуку</td>
   			<td>Цена за 100 грамм</td>			
   		</tr>
   		<tr>
   			<td>{{sweet.typeOfSweet}}</td>
   			<td><a id="first" href="{% url 'manufacturer_detail' sweet.manufacturer.id %}">{{sweet.manufacturer}}</a></td>
  			<td>{{sweet.price_for_one}}</td>
   			<td>{{sweet.price_weight}}</td>			
   		</tr>
   	</table>
   	
   		<a style="color:black;font-weight:600;font-size:250%" href="{% url 'sweet_buy' sweet.id %}">Купить</a>
   	
{% endblock %}

shop/templates/sweet/sweet_list.html
{% extends 'shop_base.html' %}
{% block title %}
	Список сладостей
{% endblock %}
{% block content %}
	<h1> Список сладостей </h1>
	<table border="3" cellpadding="10" bordercolor= "blue">
		<tr>
    		<td color="white">Название</td>
   			<td>Тип</td>
  			<td>Цена за одну штуку</td>
   			<td>Цена за 100 грамм</td>			
   		</tr>
		{% for sweet in sweets %}
		<tr>
			<td><a id="first" href="{% url 'sweet_detail' sweet.id %}">{{sweet.title}}</a></td>
			<td>{{sweet.typeOfSweet}}</td>
			<td>{{sweet.price_for_one}}</td>
			<td>{{sweet.price_weight}}</td>
		</tr>
		{% endfor %}
	</table>		
	<div class="pagination">
    <span class="step-links">
        {% if sweets.has_previous %}
            <a href="?page={{ sweets.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ sweets.number }} of {{ sweets.paginator.num_pages }}.
        </span>

        {% if sweets.has_next %}
            <a href="?page={{ sweets.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

shop/templates/sweet/sweet_nomoney.html
{% extends 'shop_base.html' %}
{% block title %}
	Недостаточно средств
{% endblock %}
{% block content %}
	<h1>{{user.username}}, у вас недостаточно средств для этой покупки</h1>
{% endblock %}

shop/templates/sweet/sweet_thanks.html
{% extends 'shop_base.html' %}
{% block title %}
	Спасибо за покупку
{% endblock %}
{% block content %}
	<h1>Покупка завершена! Спасибо!</h1>
{% endblock %}